insert into Vendedores values
('VWEM01', 'DE ALBA VILLALOBOS LILIANA LIZBETH'),
('VWEM02', 'FACIO ESPINOSA JUAN CARLOS'),
('VWEM03', 'GOMEZ CANO JOSE MIGUEL'),
('VWEM04', 'GOMEZ CASTAÑEDA MARIA FERNANDA'),
('VWEM05', 'GOMEZ LOPEZ RAFAEL');
